print('Bem vindo a Haytech Informatica')
print('')
cliente = input('Digite o nome do Cliente ')
print('')
produto = input('Digite o produto a ser comprado ')
print('')
valor_produto = float(input('Digite o valor do produto '))
print('')
desconto = int(input('Digite o desconto a ser utilizado (0-100) %'))
valor = valor_produto * (desconto / 100)
final = valor_produto - desconto
print('{}, o desconto no {} sera de {}%'.format(cliente, produto, valor))
print('')
print('Valor final do produto: {}'.format(final))
print('')
print('Agradecemos pela compra, Volte Sempre!')